# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: dr-antimonious
          template: classic
          base: header
          config_timezone: Europe/Zagreb
          
          experimental_features: --optimize-svg
          optimize: css, xml, svg
          clean_workflows: success
          repositories_skipped: WorldJobDataVisualization
          
          base_indepth: yes
          repositories_forks: yes
          repositories_affiliations: owner, collaborator, organization_member
          commits_authoring: Leo Tumbas, dr-antimonious, leotumbas, leotumbas@gmail.com, leo@advanc.eu, dr-antimonious@users.noreply.github.com
          
          plugin_habits: yes
          plugin_habits_facts: yes
          
          plugin_introduction: yes
          plugin_introduction_title: yes
          
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: Jupyter Notebook, KiCad Layout, KiCad Schematic, Microsoft Visual Studio Solution, HAProxy, XML, JSON, Shell, Markdown, INI
          plugin_languages_colors: github
          plugin_languages_details: lines
          plugin_languages_categories: data, markup, programming, prose
          
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{secrets.CLIENT_ID}}, ${{secrets.CLIENT_SECRET}}, ${{secrets.REFRESH_TOKEN}}"
          plugin_music_mode: top
          plugin_music_limit: 5
          plugin_music_user: Aidan
          plugin_music_time_range: short
          plugin_music_top_type: tracks
