# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org  (for organization related metrics)
          #  - read:user (for user related data)
          #  - repo      (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: dr-antimonious
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Zagreb
          plugin_habits: yes
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_limit: 20
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_lines: yes
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{secrets.CLIENT_ID}}, ${{secrets.CLIENT_SECRET}}, ${{secrets.REFRESH_TOKEN}}"
          plugin_music_mode: recent
          plugin_music_limit: 5
          plugin_music_user: Aidan
